@startuml Conceptual Database Model

skinparam TitleBorderRoundCorner 15
skinparam TitleBorderThickness 3
skinparam TitleBackgroundColor gray
skinparam TitleFontColor white

title Conceptual Model

object "**Clientzadnadsjasd**" as Client {
    business_name
    business_type
    business_representative
    phone_number
    email
    zone
    formal_address
    geological_address
}

object "**Driver**" as Driver {
    driver_name
    driver_document_id
    salary
    hiring_date
}
 
object "**Vehicle**" as Vehicle {
    car_brand
    car_plaque
    type_of_gas
    purchase_date
    tank_capacity
}

object "**Maintenance log**" as MaintenanceLog {
    maintenance_type
    maintenance_day
}

object "**Business Stock**" as BusinessStock {
    <Product> 
    <Quantity>
}

object "**Order**" as Order {
    <Client>
    <Product> 
    <Quantity>
    <Status>
}

object "**Product**" as Product {
    product_name
    supplier
    price
    quantity
    category_name
    subcategory_name
    is_available
}

object "**Supplier**" as Supplier {
    supplier_name
    formal_address
    phone_number
    email
    have_delivery
}

BusinessStock .> Supplier : "**get stocked**"
Vehicle  <. Driver : "**use**"
Client " ( 1...* ) " ..> "( 0...* )" Order : "**make**"
Supplier " ( * ) " --> " ( 1...* ) " Product : "**have**"
Product " ( 0...* ) " <-- BusinessStock : "**have**" 
Order .> BusinessStock : "**get products**"
Vehicle -> "( 0...* )" MaintenanceLog : \t**have**\t >

@enduml