@startuml Logical Database Model

skinparam BackgroundColor transparent

skinparam HeaderFontColor #52FF69
skinparam HeaderFontSize 18

skinparam ArrowFontSize 15
skinparam ArrowColor D3374A
skinparam ArrowThickness 2
skinparam ArrowFontColor #3FD0C4

skinparam ClassBorderColor white
skinparam ClassBorderThickness 3
skinparam ClassAttributeFontSize 14
skinparam ClassAttributeFontColor FF6127
skinparam ClassBackgroundColor #283747
skinparam ClassFontSize 15
skinparam ClassFontStyle Bold
skinparam ClassFontColor #FFB623

entity "Client" as Client {
  **PK** client_id : int <<generated>>
  **FK** geo_address_id: int
    <<GeologicalAddress.geo_address_id>>
  **FK** zone_id: int
    <<Zone.zone.id>>
  **FK** dev_interval_id: int
    <<DeliveryInterval.dev_interval_id>>
  **FK** buiness_type_id: int
    <<BusinessType.business_type_id>>
  --
  business_name: VARCHAR <<unique>>
  business_representative: VARCHAR
  phone_number: VARCHAR <<unique>>
  email: VARCHAR <<unique>>
  formal_address: VARCHAR 
}

entity "ClientXDevDay" as ClientXDevDay {
  **PK** (client_id, dev_day_id)
  **FK** client_id: int
    <<Client.client_id>>
  **FK** dev_day_id: int
    <<DeliveryDay.dev_day_id>>
}

entity "ClientOrder" as OrderC{
    **PK** client_order_id: int <<generated>>
    **FK** client_id: <<Client.client_id>>
    --
    order_status: VARCHAR
    order_date: date = CURRENT_DATE
    order_delivery_date: date
}

entity "ClientOrderDetail" as OrderDetail {
    **PK** (client_order_id, product_id)
    **FK** client_order_id: int
      <<OrderC.client_order_id>>
    **FK** product_id: int
      <<Product.product_id>>
    --
    quantity: int
}

entity "Business Stock" as BusinessStock {
    **PK FK** product_id: <<Product.product_id>>
    --
    quantity: int
}

entity "Supplier" as Supplier {
    **PK** supplier_id: int <<generated>>
    --
    supplier_name: VARCHAR <<unique>>
    formal_address: VARCHAR
    phone_number: VARCHAR <<unique>>
    email: VARCHAR <<unique>>
    have_delivery: VARCHAR {'YES', 'NO'}
}

entity "ProductCategory" as ProductCategory {
    **PK** product_category_id: int <<generated>>
    --
    product_cat_name: VARCHAR <<unique>>
}

entity "ProductSubCategory" as ProductSubCategory {
    **PK** product_subcat_id: int <<generated>>
    **FK** product_subcat_catId: 
      int <<ProductCategory.product_category_id>>
    --
    product_sub_cat_name: VARCHAR <<unique>>
}

entity "Product" as Product {
    **PK** product_id: int <<generated>>
    **FK** supplier_id: int <<Supplier.supplier_id>>
    **FK** product_cat_id: 
      int <<ProductCategory.product_category_id>>
    **FK** product_subcat_id:
      int <<ProductSubCategory.product_subcat_id>>
    --
    product_name: VARCHAR <<unique>>
    is_available: VARCHAR {'YES', 'NO'}
}

entity "SupplierOrder" as SupplierOrder {
    **PK** supplier_order_id: int <<generated>>
    **FK** supplier_id: <<Supplier.supplier_id>>
    --
   order_date: date = CURRENT_DATE
}

entity "SupplierOrderDetail" as SupplierOrderDetail {
    **FK** supplier_order_id: <<SupplierOrder.supplier_order_id>>
    **FK**product_id: <<Product.product_id>>
    --
    quantity: int
}

@enduml
